version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "@angular/*"
      versions: ["16.x"]
    - dependency-name: "@angular-devkit/build-angular"
      versions: ["16.x"]
    - dependency-name: "@angular-eslint/*"
      versions: ["16.x"]
    - dependency-name: "ng-packagr"
      versions: ["16.x"]
    - dependency-name: "typescript"
      versions: ["5.x"]
    - dependency-name: "zone"
      versions: ["0.14.x"]
