version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  # ignore packages that cannot yet be updated
  - dependency-name: "ng-packagr"
    versions: ["13.x", "14.x"]
  - dependency-name: "@angular/*"
    versions: ["13.x", "14.x"]
  - dependency-name: "@angular-devkit/build-angular"
    versions: ["13.x", "14.x"]
  - dependency-name: "@angular-eslint/*"
    versions: ["13.x", "14.x"]
  - dependency-name: "@types/node"
    versions: ["17.x", "18.x", "19.x"]
  - dependency-name: "eslint"
    versions: ["8.x"]
  - dependency-name: "rxjs"
    versions: ["7.x"]
  - dependency-name: "zone"
    versions: ["0.11.7", "0.11.8"]
  - dependency-name: "typescript"
    versions: ["4.4.x", "4.5.x", "4.6.x"]
